services:
  backend:
    build: .
    ports:
      - "80:80"
    depends_on:
        - db
    environment:
        DATABASE_URL: "postgresql://TEST_USER:TEST_PASS@db:5432/TEST_DB"
  db:
    image: postgres
    environment:
      POSTGRES_USER: "TEST_USER"
      POSTGRES_PASSWORD: "TEST_PASS"
      POSTGRES_DB: "TEST_DB"
